site_name: Ethereum Execution Spec Tests
site_url: https://execution-spec-tests.readthedocs.io/
copyright: 'Copyright: 2023, Ethereum Community'

nav:
  - Home: 'index.md'
  - Getting Started:
    - Quick Start: 'getting_started/quick_start.md'
    - Package Overview: 'getting_started/package_overview.md'
    - Writing Tests: 'getting_started/writing_tests.md'
    - Adding a Reference Spec: 'getting_started/reference_specification.md'
  - Tutorials:
    - State Transition Tests: 'tutorials/state_transition.md'
    - Blockchain Tests: 'tutorials/blockchain.md'
  - Test (Filler) Reference:
    - Withdrawals: 'fillers/withdrawals.md'
    - EIP-3651: 'fillers/eips/eip3651.md'
    - EIP-3860: 'fillers/eips/eip3860.md'
    - EIP-3855: 'fillers/eips/eip3855.md'
    - EIP-4844: 'test_case_descriptions/eip4844.md'
  - Library Reference:
    - Overview: 'library/library.md'
    - Ethereum Test Forks: 'library/ethereum_test_forks.md'
    - Ethereum Test Tools: 'library/ethereum_test_tools.md'
    - EVM Block Builder: 'library/evm_block_builder.md'
    - EVM Transition Tool: 'library/evm_transition_tool.md'
    - Pytest Plugins: 'library/pytest_plugins.md'

plugins:
  - glightbox
  - search
  - mkdocstrings

theme: readthedocs

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
      toc_depth: 4 
  - admonition
