site_name: Ethereum Execution Spec Tests
site_url: https://execution-spec-tests.readthedocs.io/
repo_url: https://github.com/ethereum/execution-spec-tests
repo_name: execution-spec-tests
edit_uri: edit/main/docs/
copyright: 'Copyright: 2023, Ethereum Community'

nav:
  - Home: 'index.md'
  - Getting Started:
    - Quick Start: 'getting_started/quick_start.md'
    - Package Overview: 'getting_started/package_overview.md'
    - Writing Tests: 'getting_started/writing_tests.md'
    - Adding a Reference Spec: 'getting_started/reference_specification.md'
  - Developer Doc:
    - Overview: 'dev/dev.md'
    - Documentation: 'dev/docs.md'
  - Tutorials:
    - State Transition Tests: 'tutorials/state_transition.md'
    - Blockchain Tests: 'tutorials/blockchain.md'
  - Test (Filler) Reference:
    - Withdrawals: 'fillers/withdrawals.md'
    - EIP-3651: 'fillers/eips/eip3651.md'
    - EIP-3860: 'fillers/eips/eip3860.md'
    - EIP-3855: 'fillers/eips/eip3855.md'
    - EIP-4844: 'test_case_descriptions/eip4844.md'
  - Library Reference:
    - Overview: 'library/library.md'
    - Ethereum Test Forks: 'library/ethereum_test_forks.md'
    - Ethereum Test Tools: 'library/ethereum_test_tools.md'
    - EVM Block Builder: 'library/evm_block_builder.md'
    - EVM Transition Tool: 'library/evm_transition_tool.md'
    - Pytest Plugins: 'library/pytest_plugins.md'

plugins:
  - glightbox
  - search
  - mkdocstrings


theme: 
  name: material
  logo: img/ETH-logo-icon.svg
  favicon: img/ETH-logo-icon.svg
  language: en
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
