site_name: Ethereum Execution Spec Tests
site_url: https://example.com/

project: 'Ethereum Execution Spec Tests'
copyright: 'Copyright: 2023, Ethereum Community'
author: 'Ethereum Community'

nav:
- Home: 'index.md'
- Getting Started:
  - Quick Start: 'getting_started/01_quick_start.md'
  - Package Overview: 'getting_started/02_package_overview.md'
  - Writing Tests: 'getting_started/03_writing_tests.md'
- Tutorials:
  - State Transition Tests: 'tutorials/01_state_transition.md'

theme: darkly
plugins:
  - glightbox

markdown_extensions:
    - toc:
        toc_depth: 2 
        permalink: "#"
    - attr_list
    - md_in_html
