[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 99

[tool.black]
line-length = 99

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"
