name: Evmone Coverage Report

on:
  pull_request:
    paths:
      - 'converted-ethereum-tests.txt' # This triggers the workflow only for changes in file.txt

jobs:
  evmone-coverage-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }} # Checks out the PR branch
          fetch-depth: 0 # Necessary to fetch all history for diff

      - name: Docker Action
        uses: ./github/actions/build-evmone-coverage@v2
        with:
          who-to-greet: 'Mona the Octocat'



