name: Build and Package Fixtures

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'fixtures'
            evm-type: 'main'
            fill-params: ''
            python: '3.12'
          - name: 'fixtures_develop'
            evm-type: 'develop'
            fill-params: '--until=Cancun'
            python: '3.12'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/build-evm
        id: evm-builder
        with:
          type: ${{ matrix.evm-type }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Run fixtures fill
        shell: bash
        run: |
          python src/entry_points/eest_utils.py init
          source env/bin/activate
          fill ${{ matrix.fill-params }}
      - name: Create fixtures info file
        shell: bash
        run: |
          echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" \
          > fixtures/info.txt
      - name: Tar fixtures output
        shell: bash
        run: |
          tar -czvf ${{ matrix.name }}.tar.gz ./fixtures
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}.tar.gz
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: .
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          files: './**'
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true