name: Post Release Jobs

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # TODO: add changelog entry updates
      - name: Update version in setup.cfg
        run: |
          NEW_VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
          sed -i "s/^version = .*/version = $NEW_VERSION/" setup.cfg
          
      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add setup.cfg
          git commit -m "Release EEST `${{ github.event.release.tag_name }}`"
          git push origin HEAD:${{ github.ref }}