name: Ethereum Testing Tools

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11']
        golang: ['1.20.5']
        solc: ['0.8.20', '0.8.21']
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout go-ethereum
        uses: actions/checkout@v2
        with:
          repository: ethereum/go-ethereum
          path: go-ethereum
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - name: Build evm cmd
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          cd $GITHUB_WORKSPACE/go-ethereum/cmd/evm
          go build .
          echo $GITHUB_WORKSPACE/go-ethereum/cmd/evm >> $GITHUB_PATH
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install solc compiler
        run: |
          RELEASE_NAME=$(curl https://binaries.soliditylang.org/linux-amd64/list.json | jq -r --arg SOLC_VERSION "${{ matrix.solc }}" '.releases[$SOLC_VERSION]')
          wget -O $GITHUB_WORKSPACE/bin/solc https://binaries.soliditylang.org/linux-amd64/$RELEASE_NAME
          chmod a+x $GITHUB_WORKSPACE/bin/solc
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
      - name: Install Aspell
        run: |
          sudo apt-get install aspell aspell-en
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox (CPython)
        run: tox
      - uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: |
            README.md
            docs/**/*.md
