name: Run Tox Verifications

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python: '3.10'
            evm-type: 'main'
            tox-cmd: 'tox run-parallel --parallel-no-spinner'
          - os: ubuntu-latest
            python: '3.11'
            evm-type: 'develop'
            tox-cmd: 'tox -e tests-develop'
          - os: ubuntu-latest
            python: '3.12'
            evm-type: 'main'
            tox-cmd: 'tox run-parallel --parallel-no-spinner'
          - os: macos-latest
            python: '3.11'
            evm-type: 'main'
            tox-cmd: 'tox run-parallel --parallel-no-spinner'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/build-evm
        id: evm-builder
        with:
          type: ${{ matrix.evm-type }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - name: Setup Tools/Dependencies Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y aspell aspell-en
      - name: Setup Tools/Dependencies macOS
        if: runner.os == 'macOS'
        run: |
          brew install aspell
          # Add additional packages on 3.11: https://github.com/ethereum/execution-spec-tests/issues/274
          if [ ${{ matrix.python }} == '3.11' ]; then brew install autoconf automake libtool; fi
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox (CPython)
        run: ${{ matrix.tox-cmd }}
      - uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: |
            README.md
            docs/**/*.md
